data class Book(
    val book_id : Long,
    val goodreads_book_id : Long,
    val best_book_id : Long,
    val work_id : Long,
    val books_count : Long,
    val isbn : Long,
    val isbn13 : Long,
    val authors : String,
    val original_publication_year : Long,
    val original_title : String,
    val title : String,
    val language_code : String,
    val average_rating : Double,
    val ratings_count : Long,
    val work_ratings_count : Long,
    val work_text_reviews_count : Long,
    val ratings_1 : Long,
    val ratings_2 : Long,
    val ratings_3 : Long,
    val ratings_4 : Long,
    val ratings_5 : Long,
    val image_url : String,
    val small_image_url : String
)